baseURL = 'http://blog.welovelsu.com/'
languageCode = 'en-us'
title = "Mark's Musings"
theme = "ananke"
SectionPagesMenu = "main"
googleAnalytics = 'G-2P94VCVLQK'
disqusShortname = 'welovelsu'
[params]
  AuthorName = 'Mark Curole'
  GitHubUser = 'tigerfansga'
  SidebarRecentLimit = 5
  Subtitle = 'JUST MY RANDOM THOUGHTS ON LIFE, FAMILY, WORK AND LSU SPORTS'

  [[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/GaTigerFanatic"

  [[params.ananke_socials]]
    name = "github"
    url = "https://github.com/tigerfansga"

[permalinks]
  posts = '/:year/:month/:title/'